### ISSUE TITLE
Users must change cg.top #include file paths

### ISSUE THREAD

**Issue by HelyRodriguez** [danialv4/Unbiased_simulations_characterize_lipid_binding#1]
After running the following minimization in a vacuum gromacs command:
gmx grompp -f ./common/min-vac.mdp -p cg.top -c ${pdb}_cg_newbox.gro -o min-vac.tpr

I received the following Fatal Error: 
Topology include file "/DATA/adaniel/software/Martini/martini_v3.0.0.itp" not found

It appears these files are all in the "common" directory that is within the "Workflow" directory of this repository. 
To fix this error, users must change the paths (for all #include files except molecule_0.itp) in the cg.top file to instead reference the files in the "common" directory that is included within the "Workflow" directory of this repository. The paths currently listed in the cg.top file likely reflect the location of the files specifically on adaniel's workstation rather than in this repository when in a given user's workstation.

**Comment by danialv4** [comment]
Thank you for your comment. I have now changed the listed paths in the "cg.top" file so they refer to the "common" directory instead.

Please note that the path for GMXRC in workflow.sh must also be specified according to the user's one.

We will be happy to help with any requests and to hear your feedback/results
